"""Generated protobuf bindings for manifest.v1.

Generated by `ci/gen_proto.py` from `proto/manifest.proto`. Do not edit
by hand; run `python ci/gen_proto.py` to regenerate.
"""

from manifest_json.proto import manifest_pb2  # noqa: F401
